# Assignment 4: Hydrologic Mapping


In [2]:
# Import numerical tools
import numpy as np

#This imports the statistics of the normal distribution
from scipy.stats import norm

# Import pyplot for plotting
import matplotlib.pyplot as plt

#Import seaborn (useful for plotting)
import seaborn as sns

# Magic function to make matplotlib inline; other style specs must come AFTER
%matplotlib inline

%config InlineBackend.figure_formats = {'svg',}

## Data entry
Here I've decided to enter the data as a matrix, in which each row represents a different station (A-D) and each column represents a different date (3/13-3/19). Units of the data are inches.

In [4]:
data = np.matrix('0.8 1.56 1 4.2 .92 1.08 0.08; 0 1.58 1.36 1.92 3.61 0.85 0.67; 0.15 1.61 0.43 2.21 0.5 0.25 0; 0.88 2.4 1.04 3.84 0.84 1.64 0.12')
print(data)

[[ 0.8   1.56  1.    4.2   0.92  1.08  0.08]
 [ 0.    1.58  1.36  1.92  3.61  0.85  0.67]
 [ 0.15  1.61  0.43  2.21  0.5   0.25  0.  ]
 [ 0.88  2.4   1.04  3.84  0.84  1.64  0.12]]


## Thiessen Polygon Method
Remember that you can copy and paste code for plotting the hyetogram from the 2/2/17 Jupyter Notebook we worked through in class.

## Inverse distance weighting method

## Isohyetal method, day 3 of the storm